name: CI
on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  find_encodings:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: python find_encodings.py

  find_encodings-utf8:
    runs-on: windows-latest
    # env:
    #   PYTHONIOENCODING: "utf-8:backslashreplace"
    #   PYTHONLEGACYWINDOWSIOENCODING: "utf-8"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: python -X utf8 find_encodings.py

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [unbuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      PYTHONIOENCODING: "utf-8:backslashreplace"
      PYTHONLEGACYWINDOWSIOENCODING: "utf-8"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup dependencies
        run: pip install -r requirements_test.txt
      - run: pytest
      - run: python -m -X utf8 mutmut run
      - run: python find_encodings.py
        if: ${{ always() }}
  
        