name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup dependencies
        run: pip install -r requirements_test.txt
      - run: pytest
      - run: mutmut
